server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.42.112:3306/menudata?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root

  redis:
    host: 192.168.42.112
    port: 6379
    database: 0

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-handlers-package: com.gzl.model.user.handler

swagger:
  enabled: true